AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    VpcConfig:
      SubnetIds:
        - subnet-0efcde944b0b461c2
      SecurityGroupIds:
        - sg-079a6d2cb621722ac
    ReservedConcurrentExecutions: 5

Resources:
  SwingApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        openapi: "3.0.0"
        info:
          version: "1.0.0"
        paths:
          /swing/balance:
            get:
              x-amazon-apigateway-integration:
                httpMethod: GET
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SwingBalanceFunction.Arn}/invocations
          /tradingview-trigger-order:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TriggerOrderFunction.Arn}/invocations

  SwingBalanceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cmd/swing
      Handler: main.go
      Runtime: go1.x
      Events:
        SwingBalance:
          Type: Api
          Properties:
            Path: /swing/balance
            Method: get
      Policies:
        - AWSLambda_FullAccess

  SwingWebHookOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cmd/swing
      Handler: main.go
      Runtime: go1.x
      Events:
        SwingWebHookOrder:
          Type: Api
          Properties:
            Path: swing/webhook-order
            Method: post
      Policies:
        - AWSLambda_FullAccess
